#!/bin/sh

for i in "$@"; do
    x=$(echo "$(basename -- "$i" ".md")");
    y=$(echo "$(dirname -- "$i")");
    pandoc "./$i" -t "latex" -o "$y/$x.pdf";
done

#for i in $(ls $*); do 
#    #x=$(echo $(basename $i ".md"));
#    #pandoc $i -t "latex" -o $x.pdf;
#done
