#!/bin/sh
a=$(grep -o 'A' $1 | wc -l)
c=$(grep -o 'C' $1 | wc -l)
g=$(grep -o 'G' $1 | wc -l)
t=$(grep -o 'T' $1 | wc -l)
cgt=$((c + g + t))

if [ "$a" -gt "$cgt" ]; then
	doma=oui
else
	doma=non	
fi

if grep -E '(.)\1{5}' $1 1>/dev/null ; then
	cons6=oui
else
	cons6=non
fi

if  grep -E '(.)(.)(.)(.)(.).\5\4\3\2\1' $1 1>/dev/null ; then
        pal11=oui
else
        pal11=non
fi

if (grep '[GTA]C[GTA]C[GTA]C[GTA]C[GTA]C' $1  || grep 'C[GTA]C[GTA]C[GTA]C[GTA]C[GTA]' $1) 1>/dev/null ; then
        altc10=oui
else
        altc10=non
fi

if (grep -E '(......).(......).*\1.\2' $1) 1>/dev/null ; then
        mut13=oui
else
        mut13=non
fi

echo "Nombre de A: $a"
echo "Nombre de C: $c"
echo "Nombre de G: $g"
echo "Nombre de T: $t"
echo "Présence du marqueur DOM-A:   $doma"
echo "Présence du marqueur CONS-6:  $cons6"
echo "Présence du marqueur PAL-11:  $pal11"
echo "Présence du marqueur ALT-C10: $altc10"
echo "Présence du marqueur MUT-13:  $mut13"
