#!/bin/sh

oui='[X]'
non='[ ]'

if [ -e "tp2.md" ]; then
	fichier=$oui
else
	fichier=$non
fi

tp="$( grep -c '# Travail pratique' tp2.md )"

if [ $tp -eq 1 ]; then
        titre=$oui
else
        titre=$non
fi

section="$( grep -E -m 1 -o  "##(.){15}" tp2.md )"
sectionEx='## Identification'

if [ "$section" = "$sectionEx" ]; then
	ident=$oui
else
        ident=$non
fi


if grep -E '^\-\ Groupe\ \ \ \ \ : (2[01]|30)$' tp2.md 1>/dev/null 2>1; then
	groupe=$oui
else
	groupe=$non
fi


if grep -E '^\-\ Enseignant\ :\ (Jean Privat|Alexandre Blondin Massé)$' tp2.md 1>/dev/null 2>1; then
	prof=$oui
else	
	prof=$non
fi


nbAuteur=$(grep -c -E '^\-\ Auteur\ \ \ \ \ : .*$' tp2.md 2>/dev/null)

if [ $nbAuteur -eq 1 ] || [ $nbAuteur -eq 2 ]; then
       auteur=$oui
else
       auteur=$non
fi

nbNomCp=$(grep -c -E '\-\ Auteur\ \ \ \ \ : [[:alpha:]]+\ [[:alpha:]]+\ \([[:upper:]]{4}[[:digit:]]{8}\)' tp2.md 1>/dev/null)

if [ $nbAuteur = $nbNomCp ]; then
	nomcp=$oui
else
	nomcp=$non
fi
	 	
nbSections=$(grep -c "^## Solution de l'exercice [0-9]$" tp2.md 2>/dev/null)
    
if [ $nbSections  -eq 9 ]; then
       sections=$oui
else
       sections=$non 
fi

nbSSections=$(grep -c "^### État de l'exercice: \(résolu\|partiellement résolu\|non résolu\)$" tp2.md 2>/dev/null)

if [ $nbSSections  -eq 9 ]; then
       ssections=$oui
else
       ssections=$non
fi

cat  <<FIN
$fichier Présence du fichier \`tp2.md\`
$titre Titre conforme
$ident Titre de la section d'identification conforme
$groupe Numéro de groupe conforme
$prof Nom de l'enseignant conforme
$nomcp Identification des auteurs conforme (nom + code permanent)
$auteur Nombre d'auteurs est 1 ou 2 (il y en a $nbAuteur)
$sections Sections de solutions conformes
$ssections Sous-sections d'état de l'exercice conformes
FIN

