#!/bin/bash

folder="$1"

if [ ! "$folder" ]; then
    exit
fi

mkdir -p "$folder"
cd "$folder"

curl -s "https://info.uqam.ca/~privat/INF1070/" | sed -n 's/.*href="\(\.\/.*\.pdf\)".*/\1/p' | sort -u > filesUniq

while read p; do
    if [ -f "${p#??}" ]; then
        echo "Le fichier https://info.uqam.ca/~privat/INF1070${p#?} a déjà été téléchargé"
    else
        echo "Téléchargement de https://info.uqam.ca/~privat/INF1070${p#?}"
        curl -O -J -s "https://info.uqam.ca/~privat/INF1070${p#?}"
    fi
done <filesUniq

rm filesUniq
